p2p:
  node:
    port: 37373-37373
    seed: beklever
    maximumExpectedPeerCount: 0
    thresholdMinConnectedPeers: 0
  kadDhtPeerDiscovery:
    enabled: true
    refreshIntervalInSec: 10
    protocolID: /klv/kad/0.0.1
    initialPeerList:
    bucketSize: 100
    routingTableRefreshIntervalInSec: 300
  sharding:
    targetPeerCount: 0
    maxIntraShardValidators: 0
    maxCrossShardValidators: 0
    maxIntraShardObservers: 0
    maxCrossShardObservers: 0
    type: NilListSharder

logs:
  LogFileLifeSpanInSec: 86400

marshalizer:
  type: protobuf